### ISSUE TITLE
Demo Site Offline - Error 404

### ISSUE THREAD

**Issue by Sn3akyP3t3** [flexdash/flexdash#18]
The demo site https://tve.github.io/flexdash is throwing error 404.

**Comment by Sn3akyP3t3** [comment]
Unfortunately, it looks like this is the sole provider of how-to documentation and I don't have any experience working with this so I'm at a loss as how to integrate and use.  I'm failing over to `node-red-contrib-uibuilder` as an alternative which is nowhere near the same thing, but at least I can move forward with that and learn how to use it.  Once this becomes available again I may return to it to work a little with it to arrive at some comparison between the two.

**Comment by tve** [comment]
If you're using FlexDash with Node-RED, the docs are at https://flexdash.github.io/docs/, also, I highly recommend to join the Node-RED forum and post issues you may have there.
