### ISSUE TITLE
props table not showing all input

### ISSUE THREAD

**Issue by Scaredon** [flexdash/flexdash#21]
input:
![elements](https://github.com/flexdash/flexdash/assets/137760585/9b9a571f-be5e-47e4-88fb-77613facf08f)

messages:

![msg](https://github.com/flexdash/flexdash/assets/137760585/ee0dcc9c-a0ed-4cde-a0a6-a7b2559e2fd8)

dashboard:

![resultDashboard](https://github.com/flexdash/flexdash/assets/137760585/88f01333-c995-4a10-9083-16ff090ee34a)

props settings:
![widgetSettings](https://github.com/flexdash/flexdash/assets/137760585/626353c6-65d9-4f49-884a-6c7aece78886)

expectation:
all three props are shown

**Comment by tve** [comment]
You can't feed properties one-by-one, the table shows the full `{ ... }` that you pass as payload, it doesn't accumulate.
